//
// Created by Steven on 10/7/2017.
//

#ifndef SHORTESTPATHPROBLEM_PROPERTIES_H
#define SHORTESTPATHPROBLEM_PROPERTIES_H

#define MAX_DIMENSION 100
#define NUMBER_MAX_LENGTH 4
#define DEFAULT_NEIGHBOR_COUNT 8

#endif //SHORTESTPATHPROBLEM_PROPERTIES_H
